version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: foto_flow_db
      POSTGRES_USER: paras_user
      POSTGRES_PASSWORD: PostgressPassword123
    ports:
      - "5433:5432"

  frontend:
    build:
      context: ./CLIENT
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    env_file:
      - ./CLIENT/.env

  backend:
    build:
      context: ./SERVER
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./SERVER/.env
    depends_on:
      - postgres

  microservice_api:
    build:
      context: ./FACE_RECOGNIZE
    container_name: microservice_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - ./FACE_RECOGNIZE:/app
    env_file:
      - ./FACE_RECOGNIZE/.env

  microservice_celery:
    build:
      context: ./FACE_RECOGNIZE
    container_name: microservice_celery
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./FACE_RECOGNIZE:/app
    env_file:
      - ./FACE_RECOGNIZE/.env
