"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const media_controller_1 = require("../Controller/media.controller");
const auth_middleware_1 = require("../Middleware/auth.middleware");
const upload_middleware_1 = require("../Middleware/upload.middleware");
const router = express_1.default.Router();
router.post("/upload", auth_middleware_1.protect, upload_middleware_1.upload.array("files", 50), media_controller_1.uploadMedia);
router.get("/", auth_middleware_1.protect, media_controller_1.getMedia);
router.delete("/delete-all", auth_middleware_1.protect, media_controller_1.deleteAllMedia);
router.post("/download-multiple", auth_middleware_1.protect, media_controller_1.downloadMultipleMedia);
router.patch("/move-to-bin", auth_middleware_1.protect, media_controller_1.moveManyToBin);
router.delete("/delete-selected", auth_middleware_1.protect, media_controller_1.deleteMedia);
router.get("/:filename/download", auth_middleware_1.protect, media_controller_1.downloadMediaFile);
router.get("/:id", auth_middleware_1.protect, media_controller_1.getMediaById);
router.delete("/:id", auth_middleware_1.protect, media_controller_1.deleteMedia);
router.patch("/:id/bin", auth_middleware_1.protect, media_controller_1.moveToBin);
exports.default = router;
